#Database settings
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: ""
  database: "koenzime"

#Miniumum amount of players required before the game starts
min-players: 2

#Match countdown (in seconds)
match-countdown: 5

#Match length (in minutes)
match-length: 2

#How signs should be displayed
sign-format:
- "&f[&2Races&f]"
- "&6%arena_name%"
- "&2%action%"

#Blocked commands while ingame
blocked-commands:
- /fly
- /god
- /gm
- /gamemode
- /heal
- /give
- /tp